// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvQmjG-ArL2BhuUv2lZgCTlgRg475KcAQ',
    appId: '1:96271247112:web:ec88d5828f4d367d3d2ebd',
    messagingSenderId: '96271247112',
    projectId: 'chat-app-8d5a8',
    authDomain: 'chat-app-8d5a8.firebaseapp.com',
    storageBucket: 'chat-app-8d5a8.firebasestorage.app',
    measurementId: 'G-25QBX6840Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGiQFlMawJtqHSNy7ZlanPF4wuqmEj3K4',
    appId: '1:96271247112:android:da38151347defbfe3d2ebd',
    messagingSenderId: '96271247112',
    projectId: 'chat-app-8d5a8',
    storageBucket: 'chat-app-8d5a8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJf1q39P3Aui1agVIwyY5lgnp46QEh2dY',
    appId: '1:96271247112:ios:7e8156cafc6a287c3d2ebd',
    messagingSenderId: '96271247112',
    projectId: 'chat-app-8d5a8',
    storageBucket: 'chat-app-8d5a8.firebasestorage.app',
    iosClientId: '96271247112-keh43ntr47fbhr0ugcsjshmkd2q2dbbb.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJf1q39P3Aui1agVIwyY5lgnp46QEh2dY',
    appId: '1:96271247112:ios:7e8156cafc6a287c3d2ebd',
    messagingSenderId: '96271247112',
    projectId: 'chat-app-8d5a8',
    storageBucket: 'chat-app-8d5a8.firebasestorage.app',
    iosClientId: '96271247112-keh43ntr47fbhr0ugcsjshmkd2q2dbbb.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterChatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvQmjG-ArL2BhuUv2lZgCTlgRg475KcAQ',
    appId: '1:96271247112:web:836c78a6357b988d3d2ebd',
    messagingSenderId: '96271247112',
    projectId: 'chat-app-8d5a8',
    authDomain: 'chat-app-8d5a8.firebaseapp.com',
    storageBucket: 'chat-app-8d5a8.firebasestorage.app',
    measurementId: 'G-BB3NF5MSTN',
  );
}
